### ISSUE TITLE
Caves Problem

### ISSUE THREAD

**Issue by rogerjx87** [Jamesits/docker-dst-server#11]
I have been try servers time but I just could not enter the sinkhole."The earth it self reject me”is what Wilson says.Maybe there is something wrong with my configuration.

**Comment by Jamesits** [comment]
Can you post a screenshot of [the console](https://dontstarve.fandom.com/wiki/Console) after you try to enter the sinkhole?

**Comment by rogerjx87** [comment]
I figure it out,It is about my configure.Thanks.
