### ISSUE TITLE
Mods Problem

### ISSUE THREAD

**Issue by rogerjx87** [Jamesits/docker-dst-server#12]
I am Trying to download some Mods in the workshop ,so i edit the"dedicated_server_mods_setup.lua"file in Mods Folder,but everytime i start the server,It just becoming default,and no mods has been download.how can i fix that.

**Comment by Jamesits** [comment]
Are you mounting `/data` inside your container to the outside to preserve its state? What arguments did you pass to `docker run`?

**Comment by rogerjx87** [comment]
Yes,I do mounting /data to the outside to preserve its state. and i am using this docker in my Synology NAS.And i did not input any arguments.here is some screenshot.
https://i.loli.net/2019/04/18/5cb8025a46260.jpg
https://i.loli.net/2019/04/18/5cb8025a5be72.png
Thanks for your reply.

**Comment by rogerjx87** [comment]
额，刚刚发现作者似乎是国人？我用的是群晖上的Docker，是图形界面，我没有输入什么特别的指令。

**Comment by Jamesits** [comment]
能否让我看一下你 Volume 的设置？如下图所示。
![image](https://user-images.githubusercontent.com/1297257/56341459-ba277b00-61e7-11e9-8958-72ab2a7da703.png)

如果方便的话，也请提供一下 Synology DSM 的版本和 Docker 包的版本。

**Comment by rogerjx87** [comment]
[https://i.loli.net/2019/04/18/5cb86a004d7dc.png](url)
群晖版本为：DSM 6.2.1-23824 Update 6；Docker包版本的话我只在日志里看到是：322646？不知道是不是正确。
[https://i.loli.net/2019/04/18/5cb86b8e4a862.png](url)

**Comment by Jamesits** [comment]
感觉好像没问题。我这边试了编辑`dedicated_server_mods_setup.lua`文件，它是会自动下载 mod 的。
你在日志里面搜索一下 mod 然后看看上下文发生了什么吧

**Comment by rogerjx87** [comment]
\docker\DST\DoNotStarveTogether\Cluster_1\mods\dedicated_server_mods_setup.lua
这个路径应该没问题吧？
日志上下文也没看到什么特别。
[https://i.loli.net/2019/04/18/5cb872b6b3b43.png](url)
不太确定这是什么情况

**Comment by Jamesits** [comment]
你看一下 updating mods…… 那里往下有没有类似这样的日志

![image](https://user-images.githubusercontent.com/1297257/56362538-b4985800-621c-11e9-8854-c94b065e26a1.png)

**Comment by rogerjx87** [comment]
有这个提示：PersistRootStorage is now /root/.klei//DoNotStarveTogether/Cluster_1/Master/ 
![snipaste_20190418_222138](https://user-images.githubusercontent.com/22608413/56367864-cb44ac00-6228-11e9-8c8a-08e69a90d852.png)

**Comment by Jamesits** [comment]
这个是正常的，/root/.klei 我是软链接到 /data 去的。你截图位置再往下翻一点呢？

以及能否传一下你改过的 `dedicated_server_mods_setup.lua` 呢

**Comment by rogerjx87** [comment]
![snipaste_20190418_222918](https://user-images.githubusercontent.com/22608413/56368164-75bccf00-6229-11e9-95b5-5d7ec279c903.png)
![snipaste_20190418_222931](https://user-images.githubusercontent.com/22608413/56368165-75bccf00-6229-11e9-8971-81cd936f9bac.png)

[dedicated_server_mods_setup.zip](https://github.com/Jamesits/docker-dst-server/files/3094828/dedicated_server_mods_setup.zip)

**Comment by zombieht** [comment]
@Jamesits 我也遇到同样的问题每次改完dedicated_server_mods_setup.lua以后重启容器，这个文件会被重写成原来初始化的样子，并且mod没有被下载

**Comment by zombieht** [comment]
我进入容器  修改/opt/steamcmd_scripts/install_dst_server脚本 把里面的validate参数去掉后就ok了，暂时运行没有问题

**Comment by Jamesits** [comment]
我猜 DST 把文件列表写错了，导致 Steam validate 的时候覆盖了一些文件。

@rogerjx87 能试一下最新的 build 吗？
