### ISSUE TITLE
How do we disable caves or do other low-level overrides?

### ISSUE THREAD

**Issue by Doc-Saintly** [Jamesits/docker-dst-server#17]
What is the easiest way to disable caves, without just making the shards unable to connect to each other?

I also wanted to generate the world with a specific seed, but it seems this requires editing a file which is stored inside the docker image.

**Comment by Jamesits** [comment]
## Disable caves server

This can be simply done by stopping the second server instance from running.

First download a copy of [supervisor.conf](https://github.com/Jamesits/docker-dst-server/blob/master/supervisor/supervisor.conf), remove everything after `[program:dst-server-cave]` (inclusive) and store it somewhere. The file will look like:

```ini
[supervisord]
nodaemon=true

[unix_http_server]
file=/var/run/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[program:dst-server-master]
user=dst
command=dontstarve_dedicated_server_nullrenderer -persistent_storage_root /data -shard Master
startsecs=40
startretries=0
autorestart=unexpected
exitcodes=0
stopwaitsecs=720
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
```

Then, mount this file into `/etc/supervisor/supervisor.conf`:

```shell
docker run -v path/to/your/new/supervisor.conf:/etc/supervisor/supervisor.conf:ro ...insert-your-other-args... -it jamesits/dst-server:latest
```

## generate the world with a specific seed

I'm not sure how to change the random seed (I searched all over the internet but Klei's documentation is just a huge mess), but what I can tell is that the docker image only contains the game server itself, all the options available during world generation is mounted by user to `/data` inside the container. You are supposed to provide your own config files. (Although if the directory is empty, a minimal example config will be copied over.)

If you can provide me instruction on how to change the seed on a normal server installation, I can dig it further. 

Another option is to use a [3rd party mod](https://forums.kleientertainment.com/forums/topic/112139-world-seeds-mod-generate-worlds-with-custom-world-seeds/) that allows you to modify the seed. I've not tried this and don't know if it works for you.

**Comment by Doc-Saintly** [comment]
Thanks for the quick response, and this docker in general! I haven't tried the mod, and the only thing I see about how to do it requires overwriting the core world generation file. Basically, you replace the call to the random number generator with the specific seed file you want. I think the cave instruction you gave is plenty for now! :)
