### ISSUE TITLE
Fill in cluster_token.txt from env var

### ISSUE THREAD

**Issue by maoxuner** [Jamesits/docker-dst-server#24]
While using image default dst configuration, container always terminates at first launch.
```
if [ ! -d "/data/DoNotStarveTogether" ]; then
        echo "Creating default server config..."
        cp -r /opt/dst_default_config/* /data
        touch /data/DoNotStarveTogether/Cluster_1/cluster_token.txt
        chown -R dst:dst /data
        echo "Done, please fill in \`DoNotStarveTogether/Cluster_1/cluster_token.txt\` with your cluster token and restart server!"
        exit
fi
```
I hope `cluster_token.txt` can be filled from env var and the process will continue.

**Comment by Jamesits** [comment]
Support for `DST_CLUSTER_TOKEN` is added in https://github.com/Jamesits/docker-dst-server/commit/2c40577eb4f09533f9e3b07febcf485a7d339ec3, please try it out

**Comment by maoxuner** [comment]
I'm going to have a try

**Comment by maoxuner** [comment]
It works find. Thx.
