### ISSUE TITLE
Supervisor configuration optimization

### ISSUE THREAD

**Issue by maoxuner** [Jamesits/docker-dst-server#25]
```bash
# ls /root
supervisord.log  supervisord.pid
```
1. Supervisor always puts log and pid file in its run path. Specifying log and pid path in `supervisor.conf` to path like `/var/run/filename` seems elegant.
   ```
   [supervisord]
   nodaemon=true
   logfile=/var/log/supervisor/supervisord.log ; (main log file;default $CWD/supervisord.log)
   pidfile=/var/run/supervisord.pid ; (supervisord pidfile;default $CWD/supervisord.pid)
   ```
2. Supervisor  uses `/etc/supervisor/supervisor.conf` as configuration by default. So it is not necessarily to pass option `-c`. See [Configuration File | Supervisor Docs](http://www.supervisord.org/configuration.html). Of course, this doesn't matter. If option `-c` is specified, the process will be much clear.

**Comment by Jamesits** [comment]
About the second problem: Supervisor is written in Python and `Explicit is better than implicit.`
