### ISSUE TITLE
Mods can not be updated

### ISSUE THREAD

**Issue by maoxuner** [Jamesits/docker-dst-server#28]
File `dedicated_server_mods_setup.lua` will be overrided with default contents every time after dst server updates. Because of this, mods can not be updated.

Prepare a full configuration directory with `dedicated_server_mods_setup.lua` modified such as `$PWD/data`, then run the container. Then you will find that `$PWD/data/DoNotStarveTogether/Cluster_1/mods/dedicated_server_mods_setup.lua` is changed after "Updating server...".
```bash
docker run --name dst -v $PWD/data:/data -p 10999-11000:10999-11000/udp -d jamesits/dst-server:steamcmd-rebase
```

Solution:
Mods symbol link `/opt/dst_server/mods` should come after dst server updating and before mods updating.

**Comment by Jamesits** [comment]
Looks like #12 came back again, fix on the way

**Comment by maoxuner** [comment]
Hello, again
软链接放到mod升级语句后面了，这样能更新么？mod更新时读取的配置是`/opt/dst_server/mods/dedicated_server_mods_setup.lua`这个文件还是`/data/DoNotStarveTogether/Cluster_1/mods/dedicated_server_mods_setup.lua`？

**Comment by Jamesits** [comment]
你说的有道理，我脑子糊涂了

**Comment by maoxuner** [comment]
老铁太给力了，速度贼快

**Comment by Jamesits** [comment]
代码改一行，CI 跑一年

**Comment by maoxuner** [comment]
> 代码改一行，CI 跑一年

主要是国内网络的问题，大部分时间都耗费在下载资源上面

**Comment by Jamesits** [comment]
我 CI 在国外跑的也一样……Docker Hub 今天网很有问题，镜像不太能 push 上去
