### ISSUE TITLE
[Error] Master Server Broadcast Error: NO_NAME

### ISSUE THREAD

**Issue by PeakGymnast** [Jamesits/docker-dst-server#33]
After i tried to rename “cluster_name” to another one which contained Chinese string on my Synology Docker and saved this changed config, then rebooting game server, an error occured “ Master Server Broadcast Error: NO_NAME”.
![批注 2020-08-23 183149](https://user-images.githubusercontent.com/62637383/90976359-eb981f80-e56e-11ea-91c3-8c1c5cfde4a6.png)

**Comment by PeakGymnast** [comment]
> ![image](https://user-images.githubusercontent.com/1297257/90979657-1de15700-e546-11ea-82a5-05f05f7fa8a3.png)
> I'm able to successfully launch the server without issue. Could you please post your `cluster.ini` here?

Here it is!!

[cluster.txt](https://github.com/Jamesits/docker-dst-server/files/5129335/cluster.txt)

**Comment by PeakGymnast** [comment]
谢谢大佬。我知道原因了。中文编码方式我没改过来，现在换成utf-8就欧克了

**Comment by Jamesits** [comment]
好
