### ISSUE TITLE
Cannot Install Mods - dedicated_server_mods_setup.lua deleted/recreated after restart

### ISSUE THREAD

**Issue by fx175** [Jamesits/docker-dst-server#34]
Hi,
Firstly, thank you for creating this docker image for a dedicated DST server!

I've managed to get my steamcmd-rebase instance running via a custom yml docker compose file.
The server starts normally and I'm able to login from the game client, but I can't seem to install mods. The "dedicated_server_mods_setup.lua" keep being deleted & recreated.

My step-by-step as follows:
1. Stop my DST container (docker stop containerid)
2. Edit the "dedicated_server_mods_setup.lua" with the list of ServerModSetup("xxxxx")
3. Restart my DST container (docker start containerid)

Everytime I do that, i noticed that all the files in the "mods" folder are modified and all my edited listing is removed.

I saw some previous Issue posted by I couldn't find any instructions on what I can do to fix this.

Thanks in advance!

**Comment by Jamesits** [comment]
Could you please post your server's full startup logs for your step 3 here?

**Comment by fx175** [comment]
[server_log.txt](https://github.com/Jamesits/docker-dst-server/files/5535602/server_log.txt)
As requested

**Comment by Jamesits** [comment]
Can you verify that the file you change is under your data directory inside `./DoNotStarveTogether/Cluster_1/mods`, not the default `/opt/dst_server/mods` one?

**Comment by fx175** [comment]
Yup, confirmed.
I declared a persistent volume in my docker compose yml.
It's the same directory where I edited the cluster.ini and cluster_token files

**Comment by Jamesits** [comment]
I noticed that no output from my `entrypoint.sh` script exist in your log file. Have you happen to modified the entrypoint of the container? Or do you mind post your `docker-compose.yml` here?

**Comment by fx175** [comment]
`version: '3.5'
services:
 dst-server:
  image: jamesits/dst-server:steamcmd-rebase
  container_name: dontstarve
  environment:
  - PUID=1000
  - PGID=1000
  - TZ=America/Denver
  volumes:
  - /data/dst:/data
  ports:
  - "10999-11000:10999-11000/udp"
  - "12346-12347:12346-12347/udp"
  stop_grace_period: 6m
  restart: "on-failure:5"
`

**Comment by fx175** [comment]
I've just tried to start over from scratch and still the same result,  `dedicated_server_mods_setup.lua` gets recreated after step 7 below.
1. Stop existing container
2. RM container
3. Delete all the folders in my data volume
4. Up new container and wait for about 10 mins
5. Stop container
6. Edit `cluster.ini` , `cluster_token`, `dedicated_server_mods_setup.lua`
7. Start container

For further reference, here's my `dedicated_server_mods_setup.lua`

```
--There are two functions that will install mods, ServerModSetup and ServerModCollectionSetup. Put the calls to the functions in this file and they will be executed on boot.

--ServerModSetup takes a string of a specific mod's Workshop id. It will download and install the mod to your mod directory on boot.
	--The Workshop id can be found at the end of the url to the mod's Workshop page.
	--Example: http://steamcommunity.com/sharedfiles/filedetails/?id=350811795
	--ServerModSetup("350811795")
ServerModSetup("786654500")
ServerModSetup("362175979")	
ServerModSetup("378160973")
ServerModSetup("1207269058")

--ServerModCollectionSetup takes a string of a specific mod's Workshop id. It will download all the mods in the collection and install them to the mod directory on boot.
	--The Workshop id can be found at the end of the url to the collection's Workshop page.
	--Example: http://steamcommunity.com/sharedfiles/filedetails/?id=379114180
	--ServerModCollectionSetup("379114180")
```

**Comment by Jamesits** [comment]
I reproduced the problem. When you restart the container, the game update process effectively reset the mods config. 

Please try the new version at https://github.com/Jamesits/docker-dst-server/commit/c819c7b61cfaaf8f6de7d83f10837ad76e26d3ce, and if there are still any issue, just comment.
