### ISSUE TITLE
Mods cannot be initated and downloaded

### ISSUE THREAD

**Issue by wstvjx** [Jamesits/docker-dst-server#37]
Here is the step I built the server.

1 Use docker-compose to create a container.
2 Stop the container 
3 edit "dedicated_server_mods_setup.lua", "cluster.ini" and "cluster_token".
4 restart the container
The result is that I can find the server with no mods.

I suspect this part logs could show the error

[00:00:01]: loaded modindex
[00:00:01]: ModIndex: Beginning normal load sequence for dedicated server.

[00:00:01]:   taskgrouplist:	default	Together
[00:00:01]:   taskgrouplist:	classic	Classic
[00:00:01]:   taskgrouplist:	cave_default	Underground
[00:00:01]:   taskgrouplist:	lavaarena_taskset	The Forge
[00:00:01]:   taskgrouplist:	quagmire_taskset	The Gorge
[00:00:01]: running main.lua

[00:00:01]: loaded modindex
[00:00:01]: ModIndex: Beginning normal load sequence for dedicated server.

RecordSteamInterfaceCreation (PID 70): STEAMUGC_INTERFACE_VERSION015 /
RecordSteamInterfaceCreation (PID 71): STEAMUGC_INTERFACE_VERSION015 /

**Comment by Jamesits** [comment]
Could you please post your docker compose yaml file and the full log (minus all sensitive information)?

**Comment by wstvjx** [comment]
Thanks for your replying. I ran my container again today, and it automatically downloads mods. Maybe it was Klei‘s problem with updating, so please close this issue. Thanks!

**Comment by Jamesits** [comment]
Sure!

**Comment by tgaff** [comment]
I've been dealing with a number of similar issues since the March QoL.  Some of them got better on their own after a few days (and hot fixes).

**Comment by kirito41dd** [comment]
I have this problem，The game is fine, but the mod is not loaded，my mod dir is only have these file:
```txt
dedicated_server_mods_setup.lua  INSTALLING_MODS.txt  MAKING_MODS.txt  modsettings.lua
```
It seems the mod was not downloaded automatically.

Here are all the logs for the container：

[logs.txt](https://github.com/Jamesits/docker-dst-server/files/7448150/logs.txt)

```shell
# cat dedicated_server_mods_setup.lua 
--There are two functions that will install mods, ServerModSetup and ServerModCollectionSetup. Put the calls to the functions in this file and they will be executed on boot.

--ServerModSetup takes a string of a specific mod's Workshop id. It will download and install the mod to your mod directory on boot.
	--The Workshop id can be found at the end of the url to the mod's Workshop page.
	--Example: http://steamcommunity.com/sharedfiles/filedetails/?id=350811795
	--ServerModSetup("350811795")

--ServerModCollectionSetup takes a string of a specific mod's Workshop id. It will download all the mods in the collection and install them to the mod directory on boot.
	--The Workshop id can be found at the end of the url to the collection's Workshop page.
	--Example: http://steamcommunity.com/sharedfiles/filedetails/?id=379114180
	--ServerModCollectionSetup("379114180")
	--
ServerModSetup("362175979")
ServerModSetup("378160973")
```

![微信截图_20211031131625](https://user-images.githubusercontent.com/35095041/139568990-11831acb-8752-433e-a61e-851e3b64ecf0.png)
