### ISSUE TITLE
关于服务器的网络连接问题

### ISSUE THREAD

**Issue by RekiDunois** [Jamesits/docker-dst-server#41]
我一开始部署的时候整个服务器的请求是通过代理的，于是地区被判定为代理所在地，导致大家连接都很卡。
但是如果我不让服务器走代理，docker 启动时候的下载就很慢，几乎下不动。
请问有没有什么好办法让 docker 下载的时候走代理，但是与官方服务器通信的时候不走代理呢？

**Comment by Jamesits** [comment]
下载和更新 mod 是一个单独的步骤，只要在这个区间内把 `http{,s}_proxy` 环境变量设置上就行了？

https://github.com/Jamesits/docker-dst-server/blob/a9643fb5463864962a9ca1062a10846c108ece8e/scripts_system/entrypoint.sh#L53-L71

**Comment by RekiDunois** [comment]
有没有办法知道下载和更新 mod 以及与官方服务器通信所使用的 url 分别是什么呢？如果是不同的 url，我只需要在代理中针对不同的 url 设置不同的分流策略就好了。
如果需要通过设置本地代理的话，可能我这边的网络结构还要修改一下。因为现在是整台机器的网络都要走一遍代理规则，而不是单个应用去设置自己的代理地址的。

**Comment by Jamesits** [comment]
这个你就要去看 steamcmd 是怎么实现的了……我不是很清楚
