### ISSUE TITLE
More worlds

### ISSUE THREAD

**Issue by Simple-Young** [Jamesits/docker-dst-server#42]
emmm,I want to know how could i create more words and start them.
more words just the dst-server have more words in Cluster_1 floder, this floder have another word except 'Cave' and 'Master',it maybe have 'Master1' floder and the 'Master1' floder represent anthoer word.
so, i want to know how can i add one or more word into dst-server.
Tips: i have find that i should revise the **supervisor.conf** file ,but i don't know how to change it.
That's all i thought.

**Comment by Jamesits** [comment]
Do you need more independent servers or you need more worlds where people can connect to one server and travel between each other? 

For the first use case, I recommend just spawning 2 docker containers. This gives you better control over the server resources each server use, and some sort of security isolation (i.e. if one server is hacked, the hacker would need to escape docker to hack the other server).

For the latter use case, I think you need to modify `supervisor.conf` and add more server configs into it. But I'm not sure if it would actually work -- I've never seen anyone doing this before. The multi server functionality is really just made for caves.

**Comment by Simple-Young** [comment]
> Do you need more independent servers or you need more worlds where people can connect to one server and travel between each other?
> 
> For the first use case, I recommend just spawning 2 docker containers. This gives you better control over the server resources each server use, and some sort of security isolation (i.e. if one server is hacked, the hacker would need to escape docker to hack the other server).
> 
> For the latter use case, I think you need to modify `supervisor.conf` and add more server configs into it. But I'm not sure if it would actually work -- I've never seen anyone doing this before. The multi server functionality is really just made for caves.

thank for reply,i will try to modify supervisor.conf

**Comment by Hicsy** [comment]
the multi-shard capability will normally link as many as you want... but beware that any more than 2 worlds will need manual wormholes linking each.

**Comment by Jamesits** [comment]
@Hicsy Thank you very much for the information!

**Comment by Hantsch** [comment]
Hi, I had the same requirement.
I did some changes and build the docker image again to allow this.
I also created a pull request if this would be something to be considered: https://github.com/Jamesits/docker-dst-server/pull/44

I outsourced the supervisor.conf to be run from the mounted volume so I can change it when needed.
Our dst server we playing on runs 5 shards, this is the supervisor.conf I am using:
```
[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/var/run/supervisord.pid

[unix_http_server]
file=/var/run/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[program:dst-server-master]
user=%(ENV_DST_USER)s
group=%(ENV_DST_GROUP)s
command=dontstarve_dedicated_server_nullrenderer -persistent_storage_root %(ENV_DST_USER_DATA_PATH)s -ugc_directory %(ENV_DST_USER_DATA_PATH)s/ugc -shard Master
startsecs=40
startretries=0
autorestart=unexpected
exitcodes=0
stopwaitsecs=720
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:dst-server-cave]
user=%(ENV_DST_USER)s
group=%(ENV_DST_GROUP)s
command=dontstarve_dedicated_server_nullrenderer -persistent_storage_root %(ENV_DST_USER_DATA_PATH)s -ugc_directory %(ENV_DST_USER_DATA_PATH)s/ugc -shard Caves
startsecs=40
startretries=0
autorestart=unexpected
exitcodes=0
stopwaitsecs=720
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:dst-server-loot]
user=%(ENV_DST_USER)s
group=%(ENV_DST_GROUP)s
command=dontstarve_dedicated_server_nullrenderer -persistent_storage_root %(ENV_DST_USER_DATA_PATH)s -ugc_directory %(ENV_DST_USER_DATA_PATH)s/ugc -shard Loot
startsecs=40
startretries=0
autorestart=unexpected
exitcodes=0
stopwaitsecs=720
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:dst-server-caveloot]
user=%(ENV_DST_USER)s
group=%(ENV_DST_GROUP)s
command=dontstarve_dedicated_server_nullrenderer -persistent_storage_root %(ENV_DST_USER_DATA_PATH)s -ugc_directory %(ENV_DST_USER_DATA_PATH)s/ugc -shard CaveLoot
startsecs=40
startretries=0
autorestart=unexpected
exitcodes=0
stopwaitsecs=720
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:dst-server-chrixworld]
user=%(ENV_DST_USER)s
group=%(ENV_DST_GROUP)s
command=dontstarve_dedicated_server_nullrenderer -persistent_storage_root %(ENV_DST_USER_DATA_PATH)s -ugc_directory %(ENV_DST_USER_DATA_PATH)s/ugc -shard ChrixWorld
startsecs=40
startretries=0
autorestart=unexpected
exitcodes=0
stopwaitsecs=720
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[group:dst-server]
programs=dst-server-master,dst-server-cave,dst-server-loot,dst-server-caveloot,dst-server-chrixworld
```

**Comment by Jamesits** [comment]
@Hantsch Thank you very much for the documentation. 

BTW, If you want to override any single file in a Docker container, you can always use `-v /path/outside:/path/inside:ro` during the container creation (available in `docker-compose.yml` too); there is no need to do it in the Dockerfile; and the file can be inside the data directory outside the container if you want to. Because editing the default `supervisord.conf` might substantially change the purpose of the container and might lead to persisted security issues, I'm not going to accept your pull request. Sorry! :)

**Comment by Jamesits** [comment]
I'm closing this for now; if you still have problems, please comment below.
