### ISSUE TITLE
Is there any way to send c_rollback(1) to the server

### ISSUE THREAD

**Issue by leftluoyi** [Jamesits/docker-dst-server#51]
If the container is successfully running with docker run **-d** option, is there any way to send `c_rollback(1)` to the server to roll back the game?

**Comment by Jamesits** [comment]
Does it work through the in-game console? I don't really know, I haven't played this game for years...

**Comment by Jamesits** [comment]
Closing due to lack of response. If you still have this problem, feel free to comment below. :)

**Comment by fjch1997** [comment]
I figured this out. Open a console window to the docker container
````
root@docker:/# supervisorctl
dst-server:dst-server-cave       RUNNING   pid 55, uptime 0:09:48
dst-server:dst-server-master     RUNNING   pid 56, uptime 0:09:48
supervisor> fg dst-server:dst-server-master
==> Press Ctrl-C to exit <==
````
Now you can enter the command you want.
