### ISSUE TITLE
语言本地化问题

### ISSUE THREAD

**Issue by naifxe** [Jamesits/docker-dst-server#56]
人物说话的语言和boss掉落的蓝图还有制作书显示的都是英文，而不是我设置的中文，我本以为是mod的问题，但是排查之后好像不是。望解答，感谢！

**Comment by haojin0323** [comment]
我在Cluster_1/cluster.ini中加了一句cluster_language = zh后游戏内显示变为中文。[cluster.ini](https://gist.github.com/Streamer0320/2ecab6b93412092490747acebb15c019)
