### ISSUE TITLE
Localized language

### ISSUE THREAD

**Issue by naifxe** [Jamesits/docker-dst-server#57]
hello,my engilsh not good.
It seems that the character language is not displayed according to the language I set,
1:Language of characters
2:Blueprints and papers dropped by boss

**Comment by naifxe** [comment]
![image](https://user-images.githubusercontent.com/41617102/208218355-f9bc3619-1436-48e4-b168-3642f40c6247.png)

**Comment by naifxe** [comment]
![image](https://user-images.githubusercontent.com/41617102/208218509-32a720cf-ebfc-4218-a416-affb9ea78e57.png)

**Comment by Jamesits** [comment]
可以讲中文，没事。

游戏里面人讲的话都是服务端下发的，语言也跟服务端一样。试试在容器启动的时候设置环境变量 `LC_ALL=zh_CN.UTF-8` 有没有用？

**Comment by naifxe** [comment]
真心感谢你的解答，我先尝试了安装中文语言包，出现了一些问题，但是我技术有限所以没有解决好，并在网上寻找答案，尝试了几遍后面使用了汉化mod后解决了

**Comment by naifxe** [comment]
但是很奇怪，其他的翻译都是本土的，就人物对话和boss掉落的雕塑图纸还有蓝图是英文的
